version: '3.8'

services:
  # Capa de Datos (MySQL)
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Microservicio de Ventas
  back-ventas:
    build:
      context: ./back-Ventas_SpringBoot/Springboot-API-REST
      dockerfile: Dockerfile
    container_name: back-ventas
    restart: unless-stopped
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend-net
      - frontend-net

  # Microservicio de Despachos
  back-despachos:
    build:
      context: ./back-Despachos_SpringBoot/Springboot-API-REST-DESPACHO
      dockerfile: Dockerfile
    container_name: back-despachos
    restart: unless-stopped
    environment:
      DB_ENDPOINT: mysql
      DB_PORT: 3306
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - backend-net
      - frontend-net

  # Frontend
  front-despacho:
    build: 
    	context: ./front_despacho
    	dockerfile: Dockerfile
    container_name: frontend_despacho
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - innovatech_net
    depends_on:
      - back-ventas
      - back-despachos
    networks:
      - frontend-net

networks:
  backend-net:
    driver: bridge
  frontend-net:
    driver: bridge

volumes:
  mysql_data:
  	driver: local