apiVersion: v1
kind: Service
metadata:
  name: backend-despacho
  namespace: innovatech-app
spec:
  selector:
    app: backend-despacho
  ports:
    - port: 3001
      targetPort: 8081
  type: ClusterIP
