apiVersion: v1
kind: Secret
metadata:
  name: despachos-secret
  namespace: innovatech-app
type: Opaque
stringData:
  DB_NAME: "db_despachos"       # reemplaza con tu valor real
  DB_USERNAME: "spring"         # reemplaza con tu valor real
  DB_PASSWORD: "password"       # reemplaza con tu valor real

apiVersion: v1
kind: Secret
metadata:
  name: ventas-secret
  namespace: innovatech-app
type: Opaque
stringData:
  DB_NAME: "db_ventas"          # reemplaza con tu valor real
  DB_USERNAME: "spring"         # reemplaza con tu valor real
  DB_PASSWORD: "password"       # reemplaza con tu valor real
