name: CI/CD innovatech app - Frontend AWS

on:
  push:
    branches: [ "deploy" ]
    paths:
      - "front_despacho/**"

jobs:
  build-and-deploy-frontend:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout codigo
      uses: actions/checkout@v3
