name: CI/CD innovatech app - DB con AWS


on:
  push:
    branches: [ "main" ]
    paths:
      - "back-Ventas_SpringBoot/Springboot-API-REST**"
  workflow_dispatch:

jobs:
  build-push-deploy-db:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS (Para el Runner)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR (Runner)
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


    - name: Build y Push - Microservicio Ventas
      env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPO_URL_DB }}
          IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
            ./back-Ventas_SpringBoot/Springboot-API-REST
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

    - name: Desplegar Base de Datos en Subred Privada vía Bastión (SSH)
      uses: appleboy/ssh-action@v1.0.3
      with:
        # --- DESTINO FINAL: INSTANCIA DE LA BASE DE DATOS ---

        host: "10.0.3.164"                          # IP privada fija de tu BD
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22

        # --- EL PUENTE (BASTIÓN): INSTANCIA DEL FRONTEND PÚBLICO ---

        proxy_host: ${{ secrets.EC2_PUBLIC_IP }}     # IP Pública de tu Frontend
        proxy_username: ec2-user
        proxy_key: ${{ secrets.EC2_SSH_KEY }}
        proxy_port: 22

        script: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | \
              docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY_URL }}

              #Levantar MySQL
              if ! docker ps | grep -q mysql-ventas; then
              docker run -d \
                --name mysql-ventas \
                --restart unless-stopped \
                -e MYSQL_ROOT_PASSWORD=${{ secrets.DB_ROOT_PASSWORD }} \
                -e MYSQL_DATABASE=${{ secrets.DB_NAME_VENTAS }} \
                -e MYSQL_USER=${{ secrets.DB_USERNAME }} \
                -e MYSQL_PASSWORD=${{ secrets.DB_PASSWORD }} \
                -p 3307:3306 \
                -v dbdata:/var/lib/mysql \
                mysql:8.0
              echo "Esperando que MySQL arranque..."
              sleep 15
            fi

            docker stop db-despacho || true
            docker rm db-despacho || true
            docker pull ${{ secrets.ECR_REGISTRY_URL }}/${{ secrets.ECR_REPO_URL_DB }}:latest
            docker run -d \
              --name db-despacho \
              --restart unless-stopped \
              -p 8080:8080 \
              -e DB_ENDPOINT=172.17.0.1 \
              -e DB_PORT=3307 \
              -e DB_NAME=${{ secrets.DB_NAME_VENTAS }} \
              -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
              -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
              ${{ secrets.ECR_REGISTRY_URL }}/${{ secrets.ECR_REPO_URL_DB }}:latest
            docker image prune -f
